STATISTICS_COLLECTION_NAME = '__STATISTICS__'

[beanstalk_conf]
host                        = 'cs2'  # 线上beanstalk内网IP
port                        = 11300      # 线上beanstalk内网port
input_tube                  = 'offline_extract_info'
output_tube                 = 'offline_entity_info'

# 分布式汇报数据库配置
[backend]
host           =   'cs0'
port            =   6379
password        =   "haizhi@)"

[server]
name = 'single_src_merger'
host = '127.0.0.1'
port = 12801
server_process_num = 1

[MYSQL]
host= 'rm-wz9x07x9567465305.mysql.rds.aliyuncs.com'
port= 3306
username= 'crawler'
password= 'huXXp7u=D'
dbname= 'crawler'

[db_backend]
type = 'mongodb'

[db_backend.hbase]
host = 'localhost'
port = 9090
rest_port = 8080

[db_backend.mongodb]
host= 'mongo0'
port= 40042
db= 'single_src'
username= 'work'
password= 'haizhi'

[logger]
level = "info"
console = false