STATISTICS_COLLECTION_NAME = '__STATISTICS__'

[beanstalk_conf]
host                        ='127.0.0.1'  # 线上beanstalk内网IP
port                        =   11300      # 线上beanstalk内网port
input_tube                  =  'enterprise_extract_info_test'
output_tube                 = 'single_src_merge_res_test'

# 分布式汇报数据库配置
[backend]
host           =   '127.0.0.1'
port            =   6379
password        =   ""

[server]
name = 'entity_extractor'
host = '127.0.0.1'
port = 12600
server_process_num = 5

[MYSQL]
host= '127.0.0.1'
port= 3306
username= 'root'
password= 'zzz'
dbname= 'multi_source'


[db_backend]
type = 'mongodb'

[db_backend.hbase]
host = 'localhost'
port = 9090
rest_port = 8080

[db_backend.mongodb]
host= '127.0.0.1'
port= 27017
db= 'single_src'
username= ''
password= ''
