STATISTICS_COLLECTION_NAME = '__STATISTICS__'

[beanstalk_conf]
host = '127.0.0.1'  # 线上beanstalk内网IP
port = 11300      # 线上beanstalk内网port
input_tube = 'final_data'
output_tube = ''


# 分布式汇报数据库配置
[backend]
host = '127.0.0.1'
port = 6379
password = "haizhi@)"

[server]
name = 'datasaver'
host = '127.0.0.1'
port = 12600
server_thread_num = 2
server_process_num = 1
process_thread_num = 4

[MYSQL]
host= '127.0.0.1'
port= 3306
username= 'work'
password= 'haizhi@)'
dbname= 'cmb_crawl'

[data_sink.mongodb]
host= '172.17.1.119'
port= 40042
db= 'app_data'
username= 'work'
password= 'haizhi'

[changeinfo.mongodb]
host= '172.17.1.119'
port= 40042
db= 'final_data'
username= 'work'
password= 'haizhi'

[kafka]
host = '182.61.26.153:9092,182.61.13.185:9092,182.61.44.214:9092'
partition_nums = 3
out_topic = 'data_saver'

[logger]
level = "info"
console = true
