middleware_module = "middleware"
# 中间件
middlewares = [
    'default',
    'hzurl',
    'useragent',
    'check',
    'httpproxy',
    'sessioncommit',
    'pageupdate'
]

[phantomjs]
restart_interval =  3600#seconds
path='/home/work/env/phantomjs/bin/phantomjs'

# 分布式汇报数据库配置
[backend]
host           =   'Crawler-DataServer2'
port            =   6379
password        =   "haizhi@)"

[server]
name = 'download'
host = '127.0.0.1'
port = 12200
server_thread_num = 32
server_process_num = 8
process_thread_num = 32

#默认请求参数
[default_request_kwargs]
method = "get"
download_type = 'simple'
time_out = 30
retry_times  =  1
check_size   = 100  # unit: B
verify     =  false


#redis配置
[redis_proxies]
host        =     'Crawler-DataServer2'    # 线上redis内网IP
password    =     'haizhi@)'
port        =     6379
database    =     8
proxy_name  =     'proxies'
proxy_test_available=24000 #hours



#beanstalk的配置
[beanstalk_conf]
host          =      'Crawler-Downloader2:Crawler-Downloader1'    # 线上beanstalk内网IP
port          =      11300      # 线上beanstalk内网port
input_tube    =      'download_req'
output_tube   =      'download_rsp'

[logger]
level = "info"
console = false
